version: '3'

services:
  mdbook:
    container_name: mdbook
    image: "ghcr.io/peaceiris/mdbook:v${MDBOOK_VERSION}"  # Docker images on GitHub Packages
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ${PWD}:/book
    command:
      - serve
      - --hostname
      - '0.0.0.0'
